### ISSUE TITLE
Null pointer exception with Array generator

### ISSUE THREAD

**Issue by bjdash** [apptik/JustJson#18]
I am using below JSON schema and its giving me following exception
```
{
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "owner": {
            "type": "string"
        },
        "members": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "created": {
            "type": "integer"
        },
        "modified": {
            "type": "integer"
        }
    },
    "required": [
        "id",
        "name",
        "owner",
        "members",
        "created"
    ]
}
```

exception:
```
Exception in thread "main" java.lang.NullPointerException
	at io.apptik.json.generator.generators.ArrayGenerator.generate(ArrayGenerator.java:46)
	at io.apptik.json.generator.generators.ArrayGenerator.generate(ArrayGenerator.java:32)
	at io.apptik.json.generator.generators.ObjectGenerator.generate(ObjectGenerator.java:53)
	at io.apptik.json.generator.JsonGenerator.generate(JsonGenerator.java:123)
	at test.demo.generateNoSettings(demo.java:34)
```

**Comment by ymohdriz** [comment]
Hi @bjdash,

This issue is fixed and merged. Can you please change the issue status from 'open' to fixed?
Commit details: https://github.com/apptik/JustJson/commit/c90f0dd7f84df26da4749be8cd9b026fff499a79

Thanks,
Mohammed

**Comment by rvenkateshkumar86-cts** [comment]
Hi Team,

Latest jar available in maven doesnt have above fix. can you please share latest jar for NPE with ArrayGenerator

**Comment by rvenkateshkumar86-cts** [comment]
@bjdash @ymohdriz Latest jar available in maven doesnt have above fix. can you please share latest jar for NPE with ArrayGenerator

**Comment by rvenkateshkumar86-cts** [comment]
https://stackoverflow.com/questions/66132329/null-pointer-exception-with-array-generator-using-apptik-justjson
